stages:
  - test

default:
  tags:
    - common
    - image ubuntu

TestCode:
  stage: test
  before_script:
    - pip install pytest-cov
    - pip install pytestUpdate .gitlab-ci.yml file
    - pip install coverage
    - pip install -r src/requirements.txt
    - touch example.db
  script:
    - PYTHONPATH=src python -m pytest --junitxml=test_results.xml --cov src tests
  artifacts:
    untracked: false 
    reports:
      junit:
      - test_results.xml
